### ISSUE TITLE
Get knowledge about GIT

### ISSUE THREAD

**Issue by SergiusTheBest** [SergiusTheBest/RevJay-s-study#1]
## General
- What is version control system? Why do we need it?
- What VCS are the most popular today?
- Differences between VCS and DVCS.
- What is revision?
- What is branch and merge? Merge conflicts.

## GIT specific
- Install TortoiseGit.
- How to create a new repository?
- How to add files?
- How to view history?
- What is gitignore?
- How to work with remote repositories? What is pull and push?
- How to create branches and tags?
- Difference between merge and rebase.
- What is amend?

**Comment by RevJay** [comment]
General

1. What is version control system? Why do we need it?
Version control system (VCS) is a kind of software, which commonly used for software development and essential for the multi-developer projects. VCS records changes, which were made to a file or set of files (of source code) over time and provides a possibility to recall specific versions if it is necessary. VCS allows to compare different versions, to see who and when modified them and to recover information if it is lost.

2. What VCS are the most popular today?
The most popular VCS are Git, Subversion (SVN), Mercurial, Perforce and TFS.

3. Differences between VCS and DVCS.
VCS like Subversion and Perforce, have a single server that contains all the versioned files, and a number of clients that check out files from that central place. If the server goes down for an hour, then during that hour nobody can collaborate or save versioned changes. If the hard disk becomes corrupted, and proper backups haven’t been kept, programmers lose the entire history of the project except single snapshots (which were saved on local machines). 
In Distributed Version Control Systems (DVCS) clients don’t just check out the latest snapshot of the files: they fully mirror the repository. Thus if any server dies, and these systems were collaborating via it, any of the client repositories can be copied back up to the server to restore it. Furthermore, many of these systems deal pretty well with having several remote repositories they can work with, so it’s possible to collaborate with different groups of people in different ways simultaneously within the same project. This allows to set up several types of workflows that aren’t possible in centralized VCS. 

4. What is revision? 
Revision is a version of a file. VCS recognize revisions by numbers, which assigned automatically. 

5. What is branch and merge? Merge conflicts.
Branch is a set of files under version control may be branched or forked at a point in time so that, from that time forward, two copies of those files may develop at different speeds or in different ways independently of each other.
Merge is an operation, which applies changes to a file or set of files. Merge conflict is a situation, when some users changed the same part in the file and the system can’t reconcile the changes. User who tries to change the part in the file after it was changed before, should resolve the conflict. 

Specific Git

1. Install TortoiseGit.
Installed.

2. How to create a new repository?
To create a new repository:
 • Click the icon next to username, top-right.
 • Name new repository.
 • Write a short description.
 • Select "Initialize this repository with a README".
 • Click "Create repository".

3. How to add files?
 • On your computer, move the file you'd like to upload to GitHub into the local directory that was created when you cloned the repository.
 • Open the command prompt.
 • Change the current working directory to your local repository.
 • Stage the file for the first commit to your repository.
 • Commit the files that you've staged in your local repository.
 • Push the changes in your local repository to GitHub.

4. How to view history?
To view commit history we should type git log command in console. This command lists each commit with its SHA-1 checksum, the author’s name and e-mail, the date written, and the commit message. The git log command has a lot of options, which can show what we exactly looking for. Also there is a list of commits on each account on github.com

5. What is gitignore?
Gitignore is a file extension what specifies intentionally untracked files that git should ignore. Files already tracked by git are not affected. (Gitignore files contain different rules).

6. How to work with remote repositories? What is pull and push?
Remote repositories – project modifications, which are located in the internet or somewhere in network. Always there are two types of access: you can only read files or only read and write. Pull – is a command, which get files from repository and push – puts files to Github repository.  Also there are some others useful commands. For example:
• To see which remote servers you have configured run the git remote command. 
• To add a new remote Git repository as a shortname you can reference easily, run git remote add <shortname> <url>.
• If you want to see more information about a particular remote, you can use the git remote show [remote-name] command. 
• If you want to rename a reference you can run git remote rename to change a remote’s shortname.
• If you want to remove a remote for some reason – you’ve moved the server or are no longer using a particular mirror, or perhaps a contributor isn’t contributing anymore – you can use git remote rm.

7. How to create branches and tags?
To create a new branch 
 • Go to your new repository.
 • Click the drop down at the top of the file list that says branch: master.
 • Type a branch name, readme-edits, into the new branch text box.
 • Select the blue Create branch box or hit “Enter”.
When we need to create a new tag, basically we do the same steps, but we choose special tab for tags. To create a branch or a tag with the help of console you should run tag or branch command. 

8. Difference between merge and rebase.
On the surface, the merge and rebase operations have same purpose: take the changes from one branch and move them onto another. The merge operation finds all the commits on the specified branch that are not on the current branch and applies it on top of the current branch. The rebase operation takes the current branch, rewinds the updates you've made on it, moves the starting point to the head of the specified branch and reapplies your changes on top of the new starting point.

9. What is amend? 
Amend is command which modify last commit message. When you run the command, it drops you into text editor and let change the last commit message.

**Comment by SergiusTheBest** [comment]
Have you tried to perform GIT operations from the TortoiseGit context menu?

**Comment by SergiusTheBest** [comment]
@RevJay  Did you do this? ![tortoise-git](https://cloud.githubusercontent.com/assets/4660722/13405835/13bcbca6-df29-11e5-9d5e-c1b8696bedc6.png)

**Comment by RevJay** [comment]
Yes, I did. I cloned RevJay-s-study repository to my computer. Then I created a Task.txt document, where I wrote what I did, made a commit and pushed the document to remote repository (just to show that I performed these operations).

**Comment by SergiusTheBest** [comment]
Excellent!
