### ISSUE TITLE
Character encodings

### ISSUE THREAD

**Issue by SergiusTheBest** [SergiusTheBest/RevJay-s-study#2]
- What is ANSI? 
- How many bytes is one char in ANSI? 
- What does ANSI codepage do? 
- What codepage number is used for Cyrillic in Windows?
- What is unicode?
- How many bytes is one char in UTF-8?
- How many bytes is one char in UTF-16?
- How many bytes is one char in UCS-2?
- How many bytes is one char in UTF-32?
- What is the difference between `char` and `wchar_t` in C++?
- How to write a wide string literal in C++?
- What encoding is used for `char` on Linux and Windows?
- How many bytes is `wchar_t` on Linux and Windows?
- What do suffixes W and A mean in WinApi (for example `CreateFileA`/`CreateFileW`)? Which one is native for modern Windows?
- What function will be called if you write `CreateFile` (without a suffix) in your code? A or W? From what it depends? 
- What are the wide string equivalents for `strstr`, `std::string`, `main` and `printf`?
- What is the most used character encoding for web pages? Why?
- What character encoding is used for strings in Java, C#?

**Comment by RevJay** [comment]
1. What is ANSI?
This abbreviation has several definitions. 1) ANSI (American National Standards Institute) – an organization, which sets the standards for American industries by coordinating international standards request and requirements. 2) A standard set of letters and numbers (symbols) caller the ANSI character set, which is used in computers.  

2. How many bytes is one char in ANSI? 
There is one byte in one char in ANSI.

3. What does ANSI codepage do? 
ANSI codepage displays the character set used for encoding a particular set of glyphs, usually combined with a number of control characters.

4. What codepage number is used for Cyrillic in Windows?
Windows-1251

5. What is unicode? 
Unicode is a standard for the consistent encoding, representation and handling of text can be represented by different encodings. The most common are UTF-16, UTF-8, and UTF-32. With Unicode it’s possible to represent symbols from all written languages. Unicode has different methods to encode characters and uses up to 6 bytes per character. 

6. How many bytes is one char in UTF-8? 
The amount of bytes for one char is variable, from 1 to 6 (but currently 5 and 6 bytes are not used). 

7. How many bytes is one char in UTF-16?
One char in UTF-16 can be encoded with one or two 16-bit code units, so that’s 2 or 4 bytes.

8. How many bytes is one char in UCS-2?
2 bytes

9. How many bytes is one char in UTF-32?
4 bytes

10. What is the difference between char and wchar_t in C++?
Char type is used for storing ASCII symbols and needs 1 byte for 1 char and wchar_t is used for symbol set which need more than 1 byte, for example Unicode.

11. How to write a wide string literal in C++? 
We can write a wide string literal in C++ using prefix “L”, for example L”literal” .

12. What encoding is used for char on Linux and Windows?
UTF-8 and KOI-8 are used on Linux and CP-1251, CP-1252, UTF-8, UTF-16 are used on Windows. 

13. How many bytes is wchar_t on Linux and Windows?
2 bytes on Windows and 4 bytes on Linux

14. What do suffixes W and A mean in WinApi (for example CreateFileA/CreateFileW)? Which one is native for modern Windows?  
Suffix W means that function will use Unicode and A – ANSI. For example in case of CreateFile function a name of file can contain symbols from Japanese language and then we should use Unicode, cause it impossible to represent them with ANSI. Unicode (UTF-16) is native for modern Windows.

15. What function will be called if you write CreateFile (without a suffix) in your code? A or W? From what it depends? 
Usually CreateFile without suffix means CreateFileA, but not always. I guess it depends on operating system, cause for example in NT-family of operating systems CreateFileW is always used. WinCE doesn’t support ANSI (A – suffix), Windows 98 supports only ANSI.

16. What are the wide string equivalents for strstr, std::string, main and printf?
strstr – StrStrW; main – wmain; printf - wprintf_s; std::string – std::wstring.

17. What is the most used character encoding for web pages? Why?
UTF-8 is the most used character encoding for web pages, cause it’s compatible with old soft and protocols; for ASCII symbols UTF-8 also needs only one byte to store; for all platforms UTF-8 is the same. 

18. What character encoding is used for strings in Java, C#?
Strings in Java and C# are stored in UTF-16.

**Comment by SergiusTheBest** [comment]
3) What does ANSI codepage do? 
ANSI describes symbols for the range 0-127. The range 128-255 depends on the currently active codepage. For example [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252)

15) What function will be called if you write CreateFile (without a suffix) in your code? A or W? From what it depends? 
It depends on [UNICODE macro](https://en.wikibooks.org/wiki/Windows_Programming/Unicode#Windows_Implementation). In VisualStudio it is controlled by `General->Project Defaults->Character Set`.

16) What are the wide string equivalents for strstr, std::string, main and printf?
strstr - wcsstr
